# Generated by Django 3.2.9 on 2021-11-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.PositiveIntegerField(verbose_name='Area Code')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
        ),
    ]
