# Generated by Django 3.2.9 on 2021-11-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Districts',
        ),
        migrations.RemoveField(
            model_name='district',
            name='id',
        ),
        migrations.AlterField(
            model_name='district',
            name='area_code',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
