# Generated by Django 3.2.9 on 2021-12-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_streets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
