# Generated by Django 3.2.9 on 2021-12-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lgoty',
            fields=[
                ('code_lgoty', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_lgoty', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Льгота',
                'verbose_name_plural': 'Льготы',
            },
        ),
    ]
