# Generated by Django 3.2.9 on 2021-12-02 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_numbers',
            fields=[
                ('phone_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('owner_IIN', models.PositiveIntegerField()),
                ('house_number', models.PositiveIntegerField()),
                ('apartment_number', models.PositiveIntegerField()),
                ('close_number_sign', models.BooleanField()),
                ('pairing_number_sign', models.BooleanField(blank=True, null=True)),
                ('street_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.streets')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
