# Generated by Django 3.2.9 on 2021-12-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0009_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('IIN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('ж', 'женщина'), ('м', 'мужчина')], max_length=1)),
                ('availability_lgoty_signs', models.BooleanField()),
                ('code_type_lgoty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.lgoty')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
                'db_table': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('owner_IIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.owners')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.phone_numbers')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
        migrations.CreateModel(
            name='Paired_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_number', models.PositiveIntegerField()),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.phone_numbers')),
            ],
            options={
                'verbose_name': 'Спаренный номер',
                'verbose_name_plural': 'Спаренные номера',
            },
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_installations', models.DateTimeField()),
                ('owner_IIN', models.PositiveIntegerField()),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.employees')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.phone_numbers')),
            ],
            options={
                'verbose_name': 'Установка',
                'verbose_name_plural': 'Установка',
            },
        ),
    ]
